project:
  type: website
      
website:
  title: "Hansol Lee"
  navbar:
    left:
      - text: "About"
        href: index.html 
      - text: "Blog"
        href: blog.html
      - text: "Research"
        href: research.html
    tools:
      - icon: google
        href: https://scholar.google.com/citations?user=vmcet8AAAAAJ&hl=en
      - icon: github
        href: https://github.com/hansorlee
      - icon: linkedin
        href: https://www.linkedin.com/in/hansol-lee-25b044293/
      - icon: envelope
        href: mailto:hansol@stanford.edu

format:
  html:
    toc: true
    theme:
      - brand

# Use the brand file for all documents in the project
brand: _brand.yml
