on:
  push:
    branches: [main, master]
  release:
    types: [published]
  workflow_dispatch: {}

name: Deploy Quarto Website

jobs:
  deploy-website:
    runs-on: ubuntu-latest

    concurrency:
      group: quarto-publish-${{ github.event_name != 'pull_request' || github.run_id }}

    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
    - name: "Check out repository"
      uses: actions/checkout@v4

    - name: "Set up Quarto"
      uses: quarto-dev/quarto-actions/setup@v2
      with:
        version: "1.7.3"  

    - name: "Set up R"
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: "4.3"

    - name: "Install system libraries for R dependencies"
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libxml2-dev \
          libcurl4-openssl-dev \
          libssl-dev \
          libblas-dev \
          liblapack-dev \
          gfortran \
          build-essential \
          pkg-config

    - name: "Install R dependencies"
      run: |
        Rscript -e 'install.packages("mirt", dependencies = TRUE, repos = "https://cloud.r-project.org")'

    - name: "Render working directory"
      uses: quarto-dev/quarto-actions/render@v2

    - name: Upload Pages artifact
      uses: actions/upload-pages-artifact@v2
      with: 
        retention-days: 1
        path: '_site'

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v2